First Fully Working Prototype
googleinterns/go-function-coverage pull request #2
Opened 2020-09-14 14:09 UTC by muratekici

2020-09-14 20:06 UTC, pratyai requested changes

2020-09-14 20:06 UTC, pratyai commented on packages/handler/BUILD.bazel
> +)
Could you format all the build files with the buildifier, please? Some small stuff like ending file with a new line will be changed then I think.

2020-09-14 20:06 UTC, pratyai commented on packages/handler/main.go
> +
Please drop the leading and trailing newlines inside the function body.

2020-09-14 20:06 UTC, pratyai commented on packages/handler/main.go
> +	duration, _ := time.ParseDuration("500ms")
duration = 500 * time.Millisecond

2020-09-15 07:30 UTC, muratekici commented on packages/handler/BUILD.bazel
> +)
Thanks, fixed it.

2020-09-24 13:07 UTC, muratekici commented
I changed the code_coverage_mode option. Now it is in the rules_go repo instead of Bazel. Other option is still in the Bazel repo so we still need to install a modified Bazel to use it.  Details are in the document. 

I also did some changes in the structure of the project.

2020-09-24 21:13 UTC, merged